# Generated by Django 5.2.7 on 2025-11-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('separador_recibos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recibodetectado',
            new_name='separador_r_procesa_187ef9_idx',
            old_name='separador_r_procesa_f381e7_idx',
        ),
        migrations.RenameIndex(
            model_name='recibodetectado',
            new_name='separador_r_nombre__b4fb07_idx',
            old_name='separador_r_nombre_b_1a8c5c_idx',
        ),
        migrations.RenameIndex(
            model_name='recibodetectado',
            new_name='separador_r_fecha_a_fdbda3_idx',
            old_name='separador_r_fecha_a_2c8b4e_idx',
        ),
    ]
