# Generated by Django 5.2.7 on 2025-11-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('separador_recibos', '0002_rename_separador_r_procesa_f381e7_idx_separador_r_procesa_187ef9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientorecibo',
            name='archivo_reporte',
            field=models.FileField(blank=True, null=True, upload_to='pdfs_procesados/'),
        ),
        migrations.AddField(
            model_name='procesamientorecibo',
            name='calidad_imagen',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', help_text='Calidad de extracción de imágenes', max_length=10),
        ),
        migrations.AddField(
            model_name='procesamientorecibo',
            name='extraer_imagenes',
            field=models.BooleanField(default=True, help_text='Extraer imágenes de alta calidad de cada recibo'),
        ),
        migrations.AddField(
            model_name='procesamientorecibo',
            name='formato_salida',
            field=models.CharField(choices=[('pdf_imagenes', 'PDF con imágenes'), ('pdf_texto', 'PDF solo texto'), ('ambos', 'Ambos formatos')], default='pdf_imagenes', help_text='Formato del archivo de salida', max_length=20),
        ),
        migrations.AddField(
            model_name='procesamientorecibo',
            name='generar_reporte',
            field=models.BooleanField(default=True, help_text='Generar reporte con estadísticas'),
        ),
        migrations.AddField(
            model_name='procesamientorecibo',
            name='tamaño_imagen',
            field=models.CharField(choices=[('pequeña', 'Pequeña'), ('mediana', 'Mediana'), ('grande', 'Grande')], default='mediana', help_text='Tamaño de las imágenes extraídas', max_length=10),
        ),
    ]
