# Generated by Django 5.2.7 on 2025-11-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('separador_recibos', '0003_procesamientorecibo_archivo_reporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesamientorecibo',
            name='calidad_imagen',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='alta', help_text='Calidad de extracción de imágenes', max_length=10),
        ),
        migrations.AlterField(
            model_name='procesamientorecibo',
            name='tamaño_imagen',
            field=models.CharField(choices=[('pequeña', 'Pequeña'), ('mediana', 'Mediana'), ('grande', 'Grande')], default='grande', help_text='Tamaño de las imágenes extraídas', max_length=10),
        ),
    ]
