# Generated by Django 5.2.7 on 2025-11-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('separador_recibos', '0005_alter_recibodetectado_fields_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientorecibo',
            name='archivo_resultado_texto',
            field=models.FileField(blank=True, null=True, upload_to='pdfs_procesados/'),
        ),
    ]
