# Generated by Django 5.2.7 on 2025-11-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('separador_recibos', '0006_procesamientorecibo_archivo_resultado_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibodetectado',
            name='pdf_individual',
            field=models.FileField(blank=True, null=True, upload_to='pdfs_individuales/'),
        ),
    ]
