# Generated by Django 5.2.7 on 2025-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departamento_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='codigo_municipio',
            field=models.CharField(max_length=10, verbose_name='Código del Municipio'),
        ),
    ]
