# Generated by Django 5.2.7 on 2025-10-24 17:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diligenciamiento', models.DateField(verbose_name='Fecha de Diligenciamiento')),
                ('nombre_razon_social', models.CharField(max_length=200, verbose_name='Nombre o Razón Social')),
                ('naturaleza_juridica', models.CharField(choices=[('PERSONA_NATURAL', 'Persona Natural'), ('PERSONA_JURIDICA', 'Persona Jurídica'), ('SOCIEDAD', 'Sociedad')], max_length=20, verbose_name='Naturaleza Jurídica')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte')], max_length=20, verbose_name='Tipo de Identificación')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('condicion_pago', models.CharField(choices=[('001', 'Contado'), ('008', 'Crédito 8 Días'), ('010', 'Crédito 10 Días'), ('015', 'Crédito 15 Días'), ('030', 'Crédito 30 Días'), ('045', 'Crédito 45 Días'), ('060', 'Crédito 60 Días'), ('OTRO', 'Otro')], max_length=10, verbose_name='Condición de Pago')),
                ('condicion_pago_otro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Otra Condición de Pago (especificar)')),
                ('datos_representante_legal', models.CharField(max_length=200, verbose_name='Datos del Representante Legal')),
                ('firma_representante', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma del Representante Legal')),
                ('sello', models.ImageField(blank=True, null=True, upload_to='sellos/', verbose_name='Sello')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_impuesto', models.CharField(choices=[('COMPRAS', 'Retención en la Fuente por Compras'), ('SERVICIOS', 'Retención en la Fuente por Servicios'), ('TRANSPORTE', 'Retención en la Fuente por Transporte'), ('OTRO', 'Retención en la Fuente por Otro Concepto')], max_length=20, verbose_name='Tipo de Impuesto')),
                ('aplica', models.BooleanField(default=False, verbose_name='¿Aplica?')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('codigo_actividad_economica', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Actividad Económica (CIIU)')),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tarifa')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('resolucion_exento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Si es exento, indicar número y fecha de resolución')),
                ('otro_concepto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especificar otro concepto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotocopia_rut', models.FileField(blank=True, null=True, upload_to='documentos/rut/', verbose_name='Fotocopia del RUT')),
                ('solicitud_vinculacion', models.FileField(blank=True, null=True, upload_to='documentos/solicitud/', verbose_name='Solicitud de Vinculación o Actualización')),
                ('certificado_camara_comercio', models.FileField(blank=True, null=True, upload_to='documentos/camara/', verbose_name='Certificado de Cámara y Comercio (No más de 30 días)')),
                ('certificacion_bancaria', models.FileField(blank=True, null=True, upload_to='documentos/bancaria/', verbose_name='Certificación Bancaria')),
                ('fotocopia_cc_representante', models.FileField(blank=True, null=True, upload_to='documentos/cc_representante/', verbose_name='Fotocopia C.C. Representante Legal')),
                ('autorizacion_datos', models.FileField(blank=True, null=True, upload_to='documentos/autorizacion/', verbose_name='Autorización para Recolección de Datos')),
                ('proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Documento Requerido',
                'verbose_name_plural': 'Documentos Requeridos',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellidos', models.CharField(max_length=200, verbose_name='Nombre y Apellidos')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
