# Generated by Django 5.2.7 on 2025-11-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departamento_municipio'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.municipio', verbose_name='Ciudad/Municipio'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='tipo_impuesto',
            field=models.CharField(choices=[('COMPRAS', 'Retención en la Fuente por Compras'), ('SERVICIOS', 'Retención en la Fuente por Servicios'), ('TRANSPORTE', 'Retención en la Fuente por Transporte'), ('ICA', 'Código Actividad Económica (CIIU)'), ('OTRO', 'Retención en la Fuente por Otro Concepto')], max_length=20, verbose_name='Tipo de Impuesto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.municipio', verbose_name='Ciudad/Municipio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.departamento', verbose_name='Departamento'),
        ),
    ]
