# Generated by Django 5.2.7 on 2025-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_documentorequerido_autorizacion_datos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='codigo_actividad_economica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Actividad Económica (CIIU)'),
        ),
    ]
